# Application secret in AWS Secrets Manager.
#
# Terraform generates ONLY the connection strings (RDS password, Redis auth
# token) — it never sees provider keys. Provider credentials (LLM/TTS/CRM/
# WhatsApp/SMTP) are added to this same secret by the operator, either here
# or in the Secrets Manager console, and rotated independently. The ECS task
# definition maps every key below to an environment variable at container
# start; nothing is written into the image, the repo, or the task definition
# itself (only the ARN + key names are).
#
# The empty S3_ACCESS_KEY / S3_SECRET_KEY values are intentional: the app
# treats an explicit empty value as "use the ECS task role" (boto3 default
# chain), so no static S3 credentials exist.

locals {
  db_url    = "postgresql://evoa:${random_password.rds.result}@${aws_db_instance.main.endpoint}/assistant"
  redis_url = "rediss://${random_password.redis.result}@${aws_elasticache_replication_group.main.primary_endpoint_address}:6379/0"
  app_secret = jsonencode({
    # Generated by Terraform:
    DATABASE_URL = local.db_url
    REDIS_URL    = local.redis_url
    # S3 via the task role (empty = default credential chain):
    S3_ENDPOINT_URL = ""
    S3_ACCESS_KEY   = ""
    S3_SECRET_KEY   = ""
    # Operator-filled (empty defaults keep the task bootable before they are):
    OPENROUTER_API_KEY = ""
    NVIDIA_API_KEY     = ""
    GEMINI_API_KEY     = ""
    ELEVENLABS_API_KEY = ""
    TTS_API_KEY        = ""
    CRM_REST_API_KEY   = ""
    WA_TOKEN           = ""
    EMAIL_USERNAME     = ""
    EMAIL_PASSWORD     = ""
  })
}

resource "aws_secretsmanager_secret" "app" {
  name                    = "${var.project}/${var.environment}/app"
  description             = "EVOA API runtime secrets (connection strings + provider keys)"
  recovery_window_in_days = 7
}

resource "aws_secretsmanager_secret_version" "app" {
  secret_id     = aws_secretsmanager_secret.app.id
  secret_string = local.app_secret
}
