"""Initial schema on PostgreSQL.

Recreates the historical schema (previously managed by inline
CREATE IF NOT EXISTS statements) with proper PostgreSQL types:

  * ``INTEGER ... AUTOINCREMENT``  -> ``BIGINT GENERATED BY DEFAULT AS IDENTITY``
  * case-insensitive unique usernames -> unique index on ``lower(username)``
  * timestamps -> ``TIMESTAMPTZ``
  * explicit indexes on the per-user scoping columns

Revision ID: 0001
Revises:
Create Date: 2026-09-23
"""

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL,
            password_hash TEXT NOT NULL,
            salt TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    # Case-insensitive username uniqueness (the previous backend enforced this
    # with a NOCASE collation; PG expresses it as a functional unique index).
    op.execute(
        "CREATE UNIQUE INDEX uq_users_username_lower ON users (lower(username))"
    )

    op.execute(
        """
        CREATE TABLE auth_sessions (
            token TEXT PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at TIMESTAMPTZ
        )
        """
    )
    op.execute("CREATE INDEX idx_auth_sessions_user ON auth_sessions (user_id)")

    op.execute(
        """
        CREATE TABLE messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id TEXT NOT NULL,
            role TEXT NOT NULL,
            content TEXT NOT NULL,
            mode TEXT NOT NULL DEFAULT 'text',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_messages_session ON messages (session_id)")

    op.execute(
        """
        CREATE TABLE memories (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id TEXT NOT NULL,
            memory_key TEXT NOT NULL,
            memory_value TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (session_id, memory_key)
        )
        """
    )

    op.execute(
        """
        CREATE TABLE audio_files (
            filename TEXT PRIMARY KEY,
            session_id TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE rate_limit_buckets (
            key TEXT PRIMARY KEY,
            window_start BIGINT NOT NULL,
            count INTEGER NOT NULL DEFAULT 1
        )
        """
    )

    op.execute(
        """
        CREATE TABLE action_audit (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT,
            username TEXT,
            channel TEXT,
            recipient TEXT,
            subject TEXT,
            message_sha1 TEXT,
            outcome TEXT,
            detail TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX idx_action_audit_user ON action_audit (user_id)")

    op.execute(
        """
        CREATE TABLE pending_actions (
            session_id TEXT PRIMARY KEY,
            action_json TEXT NOT NULL,
            created_at DOUBLE PRECISION NOT NULL
        )
        """
    )


def downgrade() -> None:
    for table in (
        "pending_actions",
        "action_audit",
        "rate_limit_buckets",
        "audio_files",
        "memories",
        "messages",
        "auth_sessions",
        "users",
    ):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
